### ISSUE TITLE
Attempted double redirect when registering

### ISSUE THREAD

**Issue by lkw657** [ncss-2015-group-4/trivia#26]
``` pytb
Uncaught exception POST /user (127.0.0.1)
    HTTPRequest(protocol='http', host='localhost:53914', method='POST', uri='/user', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'close', 'Host': 'localhost:53914', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '67', 'Accept-Encoding': 'gzip'})
    Traceback (most recent call last):
      File "redacted/trivia/tornado/web.py", line 1141, in _when_complete
        callback()
      File "redacted/trivia/tornado/web.py", line 1162, in _execute_method
        self._when_complete(method(*self.path_args, **self.path_kwargs),
      File "redacted/trivia/tornado/ncss.py", line 94, in post
        post_handler(self, *args, **kwargs)
      File "redacted/trivia/handlers/login.py", line 100, in signup_handler_post
        request.redirect("/profile")
      File "redacted/trivia/tornado/web.py", line 501, in redirect
        raise Exception("Cannot redirect after headers have been written")
    Exception: Cannot redirect after headers have been written
```

This does not seem to be effecting the operation of the website. I do not feel like looking into it further at the moment.

**Comment by auscompgeek** [comment]
This is because someone decided to try to redirect twice...

The majority of `handlers/login.py` needs a cleanup. There is quite a bit of inefficient code in there...
